# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java
env: flex

runtime_config:
  operating_system: ubuntu22
  runtime_version: "17"

manual_scaling:
  instances: 1

env_variables:
  OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
  SPRING_PROFILES_ACTIVE: "prod"
  DB_URL: DB_URL_PLACEHOLDER
  DB_USER: DB_USER_PLACEHOLDER
  DB_PASSWORD: DB_PASSWORD_PLACEHOLDER